server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drones
    username: postgres
    password: frank2830

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialectPostgreSQLDialect
        format_sql: true
    show_sql: true

  main:
    web-application-type: servlet


